import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';

/**
 * POST /api/v1/print/orders - Create a new order
 */
export async function POST(req: NextRequest) {
  try {
    const supabase = await createClient();

    // Get current user
    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await req.json();
    const {
      items,
      delivery_address,
      delivery_city,
      delivery_phone,
      delivery_notes,
      entry_point,
      chat_session_id,
    } = body;

    if (!items?.length) {
      return NextResponse.json(
        { error: 'At least one item is required' },
        { status: 400 }
      );
    }

    // Create order (order_number is auto-generated by trigger)
    const { data: order, error: orderError } = await supabase
      .from('print_orders')
      .insert({
        client_id: user.id,
        status: 'draft',
        delivery_address,
        delivery_city: delivery_city || 'Dakar',
        delivery_phone,
        delivery_notes,
        entry_point: entry_point || 'chat',
        chat_session_id,
      })
      .select()
      .single();

    if (orderError || !order) {
      console.error('[ORDERS] Failed to create order:', orderError);
      return NextResponse.json(
        { error: 'Failed to create order' },
        { status: 500 }
      );
    }

    // Create order items
    const orderItems = items.map((item: {
      product_id?: string;
      product_name: string;
      quantity: number;
      specifications?: Record<string, unknown>;
      file_ready?: boolean;
      notes?: string;
      client_price?: number;
    }, index: number) => ({
      order_id: order.id,
      product_id: item.product_id || null,
      item_number: index + 1,
      product_name: item.product_name,
      quantity: item.quantity,
      specifications: item.specifications || {},
      client_price: item.client_price || 0,
      provider_cost: 0, // Will be filled when assigned
      file_ready: item.file_ready || false,
      design_status: item.file_ready ? 'ready' : 'pending_brief',
      status: 'pending_assignment',
      requires_quote: !item.product_id, // Extended catalog items need quotes
    }));

    const { error: itemsError } = await supabase
      .from('print_order_items')
      .insert(orderItems);

    if (itemsError) {
      console.error('[ORDERS] Failed to create order items:', itemsError);
      // Cleanup the order
      await supabase.from('print_orders').delete().eq('id', order.id);
      return NextResponse.json(
        { error: 'Failed to create order items' },
        { status: 500 }
      );
    }

    // Fetch complete order with items
    const { data: completeOrder } = await supabase
      .from('print_orders')
      .select('*, print_order_items(*)')
      .eq('id', order.id)
      .single();

    // Transform to match Order interface
    if (completeOrder) {
      const { print_order_items, ...rest } = completeOrder;
      return NextResponse.json({
        ...rest,
        items: print_order_items || [],
      });
    }

    return NextResponse.json(completeOrder);
  } catch (error) {
    console.error('[ORDERS] Error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

/**
 * GET /api/v1/print/orders - List user's orders
 */
export async function GET(req: NextRequest) {
  try {
    const supabase = await createClient();
    const { searchParams } = new URL(req.url);

    // Get current user
    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const status = searchParams.get('status');
    const page = parseInt(searchParams.get('page') || '1', 10);
    const limit = parseInt(searchParams.get('limit') || '20', 10);
    const offset = (page - 1) * limit;

    // Build query
    let query = supabase
      .from('print_orders')
      .select('*, print_order_items(*)', { count: 'exact' })
      .eq('client_id', user.id)
      .order('created_at', { ascending: false })
      .range(offset, offset + limit - 1);

    if (status) {
      query = query.eq('status', status);
    }

    const { data: orders, error, count } = await query;

    if (error) {
      console.error('[ORDERS] Error:', error);
      return NextResponse.json(
        { error: 'Failed to fetch orders' },
        { status: 500 }
      );
    }

    // Transform each order to match Order interface
    const transformedOrders = (orders || []).map((order) => {
      const { print_order_items, ...rest } = order;
      return {
        ...rest,
        items: print_order_items || [],
      };
    });

    return NextResponse.json({
      orders: transformedOrders,
      total: count || 0,
      page,
      limit,
    });
  } catch (error) {
    console.error('[ORDERS] Error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
